apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-writer
  template:
    metadata:
      labels:
        app: db-writer
    spec:
      containers:
        - name: db-writer
          image: siddhesh2263/db-writer:v1.4
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: db-writer-service
spec:
  selector:
    app: db-writer
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000